### ISSUE TITLE
Tensor size issue while inference layoutlmv2

### ISSUE THREAD

**Issue by deepanshudashora** [NielsRogge/Transformers-Tutorials#86]
Hi @NielsRogge 
```
Token indices sequence length is longer than the specified maximum sequence length for this model (676 > 512). Running this sequence through the model will result in indexing errors
Traceback (most recent call last):
  File "/home/deepanshu/Music/data_first_am/inference_layoutlmv2.py", line 76, in <module>
    output_image, true_predictions, true_boxes = inference_layoutlmv2(input_image_path, checkpoints_path, labels)
  File "/home/deepanshu/Music/data_first_am/inference_layoutlmv2.py", line 41, in inference_layoutlmv2
    outputs = model(**encoding)
  File "/home/deepanshu/anaconda3/envs/layoutlmv2/lib/python3.9/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/deepanshu/anaconda3/envs/layoutlmv2/lib/python3.9/site-packages/transformers/models/layoutlmv2/modeling_layoutlmv2.py", line 1181, in forward
    outputs = self.layoutlmv2(
  File "/home/deepanshu/anaconda3/envs/layoutlmv2/lib/python3.9/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/deepanshu/anaconda3/envs/layoutlmv2/lib/python3.9/site-packages/transformers/models/layoutlmv2/modeling_layoutlmv2.py", line 879, in forward
    position_ids = position_ids.expand(input_shape)
RuntimeError: The expanded size of the tensor (676) must match the existing size (512) at non-singleton dimension 1.  Target sizes: [1, 676].  Tensor sizes: [1, 512]
```
Faced this issue while inferencing custom trained layoutlmv2
Here is the code I am using for inference 
```
# infrence function
def inference_layoutlmv2(image_path, saved_model_dir, labels):
    image = Image.open(image_path)
    image = image.convert("RGB")

    processor = LayoutLMv2Processor.from_pretrained("microsoft/layoutlmv2-base-uncased")

    encoding = processor(image, return_offsets_mapping=True, return_tensors="pt")
    offset_mapping = encoding.pop('offset_mapping')

    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
    for k,v in encoding.items():
        encoding[k] = v.to(device)

    model = LayoutLMv2ForTokenClassification.from_pretrained(saved_model_dir)
    model.to(device)
    outputs = model(**encoding)
    print(outputs.logits.shape)

    predictions = outputs.logits.argmax(-1).squeeze().tolist()
    token_boxes = encoding.bbox.squeeze().tolist()
    width, height = image.size

    is_subword = np.array(offset_mapping.squeeze().tolist())[:,0] != 0
    id2label = {idx: label for idx, label in enumerate(labels)}

    final_prediction=[]
    for i in predictions:
        if i in list(id2label.keys()):
            final_prediction.append(i)
    
    true_predictions = [id2label[pred] for idx, pred in enumerate(final_prediction) if not is_subword[idx]]
    true_boxes = [unnormalize_box(box, width, height) for idx, box in enumerate(token_boxes) if not is_subword[idx]]

    draw = ImageDraw.Draw(image)
    font = ImageFont.load_default()

    for prediction, box in zip(true_predictions, true_boxes):
        predicted_label = iob_to_label(prediction).lower()
        draw.rectangle(box, outline=(255,0,0))
        draw.text((box[0]+10, box[1]-10), text=predicted_label, fill=(255,0,255), font=font)
    image.save("result1.jpg")

    return image, true_predictions, true_boxes
```

**Comment by purnasai** [comment]
Hi @deepanshudashora , your processor is giving the encodings of size 676, but I think the model was trained with max length  = 512. so keep truncation= True in the training phase might work. 
`self.processor(image, words, boxes=boxes, word_labels=wordlabels, 
                                        padding="max_length", truncation=True, return_tensors="pt")`
please let me know the result.

**Comment by deepanshudashora** [comment]
> Hi @deepanshudashora , your processor is giving the encodings of size 676, but I think the model was trained with max length = 512. so keep truncation= True in the training phase might work. `self.processor(image, words, boxes=boxes, word_labels=wordlabels, padding="max_length", truncation=True, return_tensors="pt")` please let me know the result.

"It worked", thanks a lot for help

**Comment by deepanshudashora** [comment]
One more question I have, how many epochs should we train the model? If we are going for custom use case

**Comment by purnasai** [comment]
Hi @deepanshudashora, It Depends on the data, optimizer, learning rate, image size, and a lot more. Use the trial and error method. but I would foresee to @NielsRogge reply on this.
